/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
  interface Routes {
    "sanctum.csrf-cookie": {
        "uri": "sanctum\/csrf-cookie",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web"
        ]
    },
    "users.index": {
        "uri": "users",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web"
        ]
    },
    "users.create": {
        "uri": "users\/create",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web"
        ]
    },
    "users.store": {
        "uri": "users",
        "methods": [
            "POST"
        ],
        "parameters": [],
        "middleware": [
            "web"
        ]
    },
    "users.show": {
        "uri": "users\/{user}",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [
            {
                "name": "user",
                "required": true,
                "binding": "id"
            }
        ],
        "middleware": [
            "web"
        ]
    },
    "users.edit": {
        "uri": "users\/{user}\/edit",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [
            {
                "name": "user",
                "required": true
            }
        ],
        "middleware": [
            "web"
        ]
    },
    "users.update": {
        "uri": "users\/{user}",
        "methods": [
            "PUT",
            "PATCH"
        ],
        "parameters": [
            {
                "name": "user",
                "required": true,
                "binding": "id"
            }
        ],
        "middleware": [
            "web"
        ]
    },
    "users.destroy": {
        "uri": "users\/{user}",
        "methods": [
            "DELETE"
        ],
        "parameters": [
            {
                "name": "user",
                "required": true,
                "binding": "id"
            }
        ],
        "middleware": [
            "web"
        ]
    },
    "dashboard": {
        "uri": "dashboard",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth",
            "verified",
            "web"
        ]
    },
    "profile.edit": {
        "uri": "profile",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "profile.update": {
        "uri": "profile",
        "methods": [
            "PATCH"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "profile.destroy": {
        "uri": "profile",
        "methods": [
            "DELETE"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "register": {
        "uri": "register",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "login": {
        "uri": "login",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "password.request": {
        "uri": "forgot-password",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "password.email": {
        "uri": "forgot-password",
        "methods": [
            "POST"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "password.reset": {
        "uri": "reset-password\/{token}",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [
            {
                "name": "token",
                "required": true
            }
        ],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "password.store": {
        "uri": "reset-password",
        "methods": [
            "POST"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "verification.notice": {
        "uri": "verify-email",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "verification.verify": {
        "uri": "verify-email\/{id}\/{hash}",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [
            {
                "name": "id",
                "required": true
            },
            {
                "name": "hash",
                "required": true
            }
        ],
        "middleware": [
            "web",
            "auth",
            "signed",
            "throttle:6,1"
        ]
    },
    "verification.send": {
        "uri": "email\/verification-notification",
        "methods": [
            "POST"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth",
            "throttle:6,1"
        ]
    },
    "password.confirm": {
        "uri": "confirm-password",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "password.update": {
        "uri": "password",
        "methods": [
            "PUT"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "logout": {
        "uri": "logout",
        "methods": [
            "POST"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    }
}
}
export {};
