/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "home": [],
    "book.index": [],
    "book.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "book.rent": [
        {
            "name": "id",
            "required": true
        }
    ],
    "book.reserve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "book.rent.create": [
        {
            "name": "id",
            "required": true
        }
    ],
    "book.reserve.create": [
        {
            "name": "id",
            "required": true
        }
    ],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "api.book.index": []
}
  interface Routes {
    "sanctum.csrf-cookie": {
        "uri": "sanctum\/csrf-cookie",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web"
        ]
    },
    "home": {
        "uri": "\/",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web"
        ]
    },
    "book.index": {
        "uri": "book",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web"
        ]
    },
    "book.show": {
        "uri": "book\/{id}",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [
            {
                "name": "id",
                "required": true
            }
        ],
        "middleware": [
            "web"
        ]
    },
    "book.rent": {
        "uri": "book\/{id}\/rent",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [
            {
                "name": "id",
                "required": true
            }
        ],
        "middleware": [
            "web"
        ]
    },
    "book.reserve": {
        "uri": "book\/{id}\/reserve",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [
            {
                "name": "id",
                "required": true
            }
        ],
        "middleware": [
            "web"
        ]
    },
    "book.rent.create": {
        "uri": "book\/{id}\/rent",
        "methods": [
            "POST"
        ],
        "parameters": [
            {
                "name": "id",
                "required": true
            }
        ],
        "middleware": [
            "web"
        ]
    },
    "book.reserve.create": {
        "uri": "book\/{id}\/reserve",
        "methods": [
            "POST"
        ],
        "parameters": [
            {
                "name": "id",
                "required": true
            }
        ],
        "middleware": [
            "web"
        ]
    },
    "dashboard": {
        "uri": "dashboard",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth",
            "verified"
        ]
    },
    "profile.edit": {
        "uri": "profile",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "profile.update": {
        "uri": "profile",
        "methods": [
            "PATCH"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "profile.destroy": {
        "uri": "profile",
        "methods": [
            "DELETE"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "register": {
        "uri": "register",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "login": {
        "uri": "login",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "password.request": {
        "uri": "forgot-password",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "password.email": {
        "uri": "forgot-password",
        "methods": [
            "POST"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "password.reset": {
        "uri": "reset-password\/{token}",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [
            {
                "name": "token",
                "required": true
            }
        ],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "password.store": {
        "uri": "reset-password",
        "methods": [
            "POST"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "guest"
        ]
    },
    "verification.notice": {
        "uri": "verify-email",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "verification.verify": {
        "uri": "verify-email\/{id}\/{hash}",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [
            {
                "name": "id",
                "required": true
            },
            {
                "name": "hash",
                "required": true
            }
        ],
        "middleware": [
            "web",
            "auth",
            "signed",
            "throttle:6,1"
        ]
    },
    "verification.send": {
        "uri": "email\/verification-notification",
        "methods": [
            "POST"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth",
            "throttle:6,1"
        ]
    },
    "password.confirm": {
        "uri": "confirm-password",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "password.update": {
        "uri": "password",
        "methods": [
            "PUT"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "logout": {
        "uri": "logout",
        "methods": [
            "POST"
        ],
        "parameters": [],
        "middleware": [
            "web",
            "auth"
        ]
    },
    "api.book.index": {
        "uri": "api\/books",
        "methods": [
            "GET",
            "HEAD"
        ],
        "parameters": [],
        "middleware": [
            "web"
        ]
    }
}
}
export {};
